services:
  server:
    build: ./server
    container_name: chatlance-server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: chatlance-client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules